apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
      name: mysql-service
      app: demo-voting-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      app: mysql-wp
      env: production
    
